//! sql438: `id int GENERATED ALWAYS AS IDENTITY DEFAULT 0` -- a column
//! defined as a SQL-standard identity column can NOT also have an
//! explicit DEFAULT clause; the identity sequence IS the default. PG
//! raises 42601 ("multiple default values specified for column"). The
//! same goes for `GENERATED BY DEFAULT AS IDENTITY DEFAULT ...`. Almost
//! always a leftover from a refactor away from a SERIAL/sequence
//! pattern -- drop the DEFAULT.

use crate::clause_scan::is_word;
use crate::{Diagnostic, LintRule, Severity};
use dsl_catalog::Catalog;
use dsl_parse::Statement;
use dsl_resolve::Scope;
use text_size::TextRange;

pub struct Rule;

impl LintRule for Rule {
  fn code(&self) -> &'static str {
    "sql438"
  }
  fn default_severity(&self) -> Severity {
    Severity::Error
  }

  fn check(&self, source: &str, stmt: &Statement, _scope: &Scope, _catalog: &Catalog, out: &mut Vec<Diagnostic>) {
    let (start, raw) = crate::stmt_body(stmt, source);
    let cleaned = crate::textutil::strip_noise_full(raw);
    let upper = cleaned.to_ascii_uppercase();
    let ub = upper.as_bytes();
    let n = ub.len();
    // Only consider CREATE TABLE / ALTER TABLE statements -- look for
    // the IDENTITY keyword first (cheap), then for a DEFAULT keyword
    // following it within the same column-def block.
    if !find_word(ub, b"CREATE") && !find_word(ub, b"ALTER") {
      return;
    }
    let mut i = 0usize;
    while i + 8 <= n {
      if &ub[i..i + 8] == b"IDENTITY"
        && (i == 0 || !is_word(ub[i - 1] as char))
        && (i + 8 == n || !is_word(ub[i + 8] as char))
      {
        // Look ahead within the same column-def: walk until comma or
        // close-paren at the same paren depth. If we encounter a
        // word-bounded DEFAULT in that span, flag.
        let mut depth: i32 = 0;
        let mut j = i + 8;
        while j < n {
          let c = ub[j];
          if c == b'(' {
            depth += 1;
            j += 1;
            continue;
          }
          if c == b')' {
            if depth == 0 {
              break;
            }
            depth -= 1;
            j += 1;
            continue;
          }
          if depth == 0 && c == b',' {
            break;
          }
          if depth == 0
            && j + 7 <= n
            && &ub[j..j + 7] == b"DEFAULT"
            && (j == 0 || !is_word(ub[j - 1] as char))
            && (j + 7 == n || !is_word(ub[j + 7] as char))
          {
            let abs_s = start + i;
            let abs_e = start + j + 7;
            out.push(Diagnostic {
              code: "sql438",
              severity: Severity::Error,
              message: "column has GENERATED ... AS IDENTITY and also DEFAULT -- PG raises 42601 \"multiple default values specified for column\"; the identity sequence is the default, so drop the DEFAULT clause".into(),
              range: TextRange::new((abs_s as u32).into(), (abs_e as u32).into()),
            });
            return;
          }
          j += 1;
        }
        i = j.max(i + 8);
        continue;
      }
      i += 1;
    }
  }
}

fn find_word(ub: &[u8], w: &[u8]) -> bool {
  let m = w.len();
  let n = ub.len();
  let mut i = 0usize;
  while i + m <= n {
    if &ub[i..i + m] == w
      && (i == 0 || !is_word(ub[i - 1] as char))
      && (i + m == n || !is_word(ub[i + m] as char))
    {
      return true;
    }
    i += 1;
  }
  false
}
