//! Rule titles, generated from each rule module's `//! sqlNNN: ...`
//! doc comment.
//!
//! DO NOT EDIT BY HAND. Regenerate with:
//!
//! ```text
//! cargo test -p dsl-analysis --test rule_reference -- --ignored
//! ```
//!
//! The doc comment is the single source of truth: it sits next to the
//! implementation, so it is the thing that actually gets updated when a
//! rule changes. `rule_reference` fails the build if this file or
//! `docs/rules.md` drifts away from it.

/// One-line summary for a diagnostic code, or `None` if unknown.
pub fn title(code: &str) -> Option<&'static str> {
  TITLES.binary_search_by_key(&code, |(c, _)| c).ok().map(|i| TITLES[i].1)
}

/// Every rule code paired with its summary, sorted by code so `title`
/// can binary-search.
pub static TITLES: &[(&str, &str)] = &[
  ("sql001", "table referenced by FROM / JOIN / UPDATE / DELETE / INSERT INTO does not exist in the catalog"),
  ("sql002", "column reference does not exist in any in-scope table"),
  ("sql003", "unqualified column reference exists in more than one in-scope table; the user must qualify it"),
  ("sql010", "UNION / INTERSECT / EXCEPT column-count mismatch"),
  ("sql013", "UPDATE or DELETE without a WHERE clause"),
  ("sql014", "implicit cross join"),
  (
    "sql015",
    "comparison with NULL using `=` or `<>` (or `!=`). Always yields NULL; the user almost always meant `IS NULL`...",
  ),
  ("sql016", "`INSERT INTO t SELECT *` is arity-fragile"),
  ("sql017", "SELECT mixes aggregates with bare column references but the bare columns are not all listed in GROUP BY"),
  (
    "sql018",
    "`NOT IN (subquery)` is dangerous when the subquery can return NULL. Postgres treats `x NOT IN (NULL)` as...",
  ),
  ("sql020", "deprecated / non-recommended function call"),
  ("sql021", "prefer the declared alias over the bare table name"),
  ("sql030", "trigger function body has no RETURN"),
  (
    "sql031",
    "`RETURN <literal>` type doesn't match declared `RETURNS <type>`. Catches the easy literal-return mismatches...",
  ),
  ("sql032", "bare `RETURN;` inside a function that declares a non-void return type"),
  (
    "sql036",
    "`RAISE EXCEPTION` (or NOTICE/WARNING/etc.) format string `%` placeholder count doesn't match the supplied...",
  ),
  ("sql037", "`SELECT"),
  ("sql038", "`INSERT INTO t (a, b) VALUES (1)`"),
  ("sql039", "`INSERT INTO t (col1, col2) VALUES (lit1, lit2)` literal types must match the target column types"),
  ("sql040", "an `IMMUTABLE` function body calls a known `VOLATILE` built-in"),
  ("sql041", "`LANGUAGE sql` function body references `NEW` or `OLD`"),
  ("sql042", "`UPDATE <table> SET <col> = ...` where `<col>` is not in the target table's catalog definition"),
  ("sql043", "`DELETE FROM <tbl>` without WHERE inside a function body"),
  ("sql044", "`EXIT` / `CONTINUE` used outside a LOOP / WHILE / FOR block"),
  (
    "sql045",
    "unreachable code after an unconditional `RETURN` or `RAISE EXCEPTION`. Postgres won't error on dead code but...",
  ),
  (
    "sql046",
    "`CREATE TABLE` without a PRIMARY KEY. Heap tables without a primary key cause replication, ORM, and audit...",
  ),
  ("sql048", "`INSERT INTO t VALUES (...)` without a column list. Positional INSERT works but is fragile"),
  (
    "sql050",
    "a column or table identifier in CREATE TABLE matches a PG reserved keyword. Postgres still accepts it but...",
  ),
  ("sql051", "`LIMIT` without `ORDER BY` produces non-deterministic rows"),
  ("sql052", "`LIKE 'plain string'`"),
  ("sql054", "`WHERE x = true` / `WHERE x = false`"),
  ("sql055", "`WHERE (single condition)`"),
  ("sql056", "`UNION` (deduplicates) is often slower than `UNION ALL` and used by mistake"),
  ("sql058", "`CASE WHEN"),
  ("sql061", "bare `NULL` inside `VALUES (...)` without an explicit cast"),
  ("sql062", "`SAVEPOINT x` declared but never `RELEASE`d (or rolled back to)"),
  ("sql064", "`"),
  ("sql065", "`GROUP BY 1, 2`"),
  ("sql068", "BEGIN / COMMIT pair wrapping a single statement"),
  ("sql069", "column declared `NOT NULL` but `DEFAULT NULL`"),
  ("sql072", "`SELECT ... FOR UPDATE` without a WHERE clause locks every row of the target table"),
  ("sql074", "`WHERE x IN (a, b, c, ...)` with > 50 items"),
  ("sql075", "column declared as `TIME WITH TIME ZONE` (alias `TIMETZ`). PG docs recommend against TIMETZ"),
  ("sql076", "`LIMIT -1` / `OFFSET -1`"),
  ("sql081", "`ORDER BY random()`"),
  ("sql083", "`INSERT INTO t (id, ...)` referencing the primary key without `ON CONFLICT`"),
  ("sql084", "`COUNT(1)` is equivalent to `COUNT(*)`"),
  ("sql085", "`NULLIF(x, x)` always returns NULL"),
  ("sql087", "`x BETWEEN <high> AND <low>`"),
  ("sql088", "`LIKE '%foo'`"),
  ("sql089", "two `RAISE EXCEPTION` calls back-to-back"),
  ("sql090", "PG 17 added `GROUP BY ALL` shorthand"),
  ("sql091", "`COMMENT ON ... IS ''`"),
  ("sql093", "`SELECT DISTINCT count(...) FROM t`"),
  ("sql094", "`CASE` expressions nested more than 3 deep"),
  (
    "sql095",
    "`x IS NOT DISTINCT FROM NULL` is just `x IS NULL`; the other form is `x IS DISTINCT FROM NULL` ≡ `x IS NOT...",
  ),
  ("sql096", "`INSERT INTO t VALUES (1, 2, );`"),
  ("sql097", "`SELECT col FROM nothing`"),
  (
    "sql098",
    "more than one `WHERE` clause in the same statement (outside parentheses/subqueries). Usually a copy/paste...",
  ),
  ("sql099", "`ORDER BY 1, 2`"),
  ("sql101", "`SELECT DISTINCT ON (x) ... FROM t` without an `ORDER BY` that starts with `x`"),
  ("sql104", "`CHAR(n)` / `CHARACTER(n)`"),
  ("sql105", "`TRUNCATE t` without `CASCADE`"),
  ("sql107", "comparing a `jsonb` column to a text literal without `::text` / `::jsonb`"),
  ("sql109", "`length(text_col)` returns *bytes*. Use `char_length` for characters"),
  ("sql111", "`LOCK TABLE` outside an explicit transaction has no effect beyond the single statement"),
  (
    "sql112",
    "`generate_series(...)` in a FROM clause without an alias ends up named `generate_series` which makes queries...",
  ),
  ("sql113", "`TIMESTAMP` without time zone"),
  ("sql115", "`jsonb_set(col, path, val)`"),
  ("sql116", "bare `NUMERIC` / `DECIMAL`"),
  ("sql117", "`INSERT INTO t (col) VALUES ('true')` where `col` is boolean"),
  ("sql118", "`SELECT ... INTO foo FROM t` at the top level is **DDL**"),
  ("sql119", "`SET TRANSACTION ISOLATION LEVEL ...` must be the **first** statement after `BEGIN`"),
  ("sql120", "`SELECT DISTINCT ... GROUP BY ...`"),
  ("sql121", "comparing a text expression to an int literal in WHERE. Common bug"),
  ("sql122", "`LIKE` inside a query without explicit `COLLATE`"),
  (
    "sql123",
    "`\\n`, `\\t`, `\\\\` inside a plain `'...'` string. PG 9.1+ defaults to `standard_conforming_strings = on`",
  ),
  ("sql124", "`WITH t AS (SELECT"),
  ("sql125", "`EXPLAIN ANALYZE INSERT/UPDATE/DELETE`"),
  ("sql126", "DML inside a PL/pgSQL function without a subsequent `GET DIAGNOSTICS rows = ROW_COUNT`"),
  ("sql127", "`UPDATE t SET ... FROM other` without a WHERE that joins `t` and `other`"),
  ("sql128", "`GRANT ... TO PUBLIC`"),
  ("sql130", "multiple `TRUNCATE` statements in one transaction. PG supports `TRUNCATE a, b, c` directly"),
  ("sql131", "`RAISE NOTICE 'value is %s'`"),
  ("sql132", "`SELECT ... FOR UPDATE` inside the recursive arm of a CTE is forbidden by PG"),
  ("sql133", "`GRANT ... WITH GRANT OPTION` lets the grantee re-grant the privilege chain to anyone else"),
  ("sql134", "`VACUUM` cannot run inside an explicit transaction block"),
  ("sql135", "`SET ROLE x` inside a transaction without a matching `RESET ROLE`"),
  ("sql136", "`COPY t FROM 'file'` without a `FORMAT` clause"),
  ("sql137", "bare `LISTEN <channel>` in a session that never `UNLISTEN`s"),
  ("sql138", "`SELECT DISTINCT (col)::text FROM t`"),
  ("sql139", "`UNIQUE` on a nullable column with `NULLS DISTINCT` (the PG default)"),
  ("sql140", "`CREATE TRIGGER ... AFTER INSERT ... WHEN (OLD.x ...)`"),
  ("sql141", "`ALTER TYPE x ADD VALUE 'y'` cannot run inside an explicit transaction block"),
  ("sql142", "`CREATE [OR REPLACE] FUNCTION ... IMMUTABLE` whose body issues DDL (CREATE, ALTER, DROP, TRUNCATE)"),
  ("sql143", "`INSERT/UPDATE/DELETE ... RETURNING ...` inside a PL/pgSQL block without `INTO <vars>` or `STRICT`"),
  ("sql144", "`CREATE TRIGGER ... AFTER DELETE ... WHEN (NEW.x ...)`"),
  (
    "sql145",
    "column `DEFAULT now()` (or any volatile expression) freezes the value at insert time, which is usually fine",
  ),
  (
    "sql146",
    "`VARCHAR` / `CHARACTER VARYING` without an explicit length. Unbounded VARCHAR is effectively TEXT but with...",
  ),
  ("sql148", "array subscript `arr[0]` or `arr[-1]`"),
  ("sql149", "`UPDATE t SET x = x`"),
  ("sql150", "`CASE WHEN"),
  ("sql151", "`SELECT ... FROM t, generate_series(t.col, 10)`"),
  (
    "sql152",
    "`BEGIN` for a transaction that needs to UPDATE/DELETE many rows without an explicit `LOCK TABLE` or `FOR...",
  ),
  ("sql153", "`now() + 1`, `created_at + 30`"),
  (
    "sql154",
    "`SELECT count(*) FROM t WHERE ...` (no GROUP BY) returns **one row** even when the WHERE matches nothing",
  ),
  ("sql155", "`TRUNCATE t RETURNING ...`"),
  ("sql156", "`SELECT ... INTO STRICT var` inside PL/pgSQL without a surrounding EXCEPTION block. STRICT raises..."),
  ("sql157", "`RAISE EXCEPTION ... USING ERRCODE = my_var`"),
  ("sql158", "`PERFORM <select>` inside PL/pgSQL where the SELECT calls no function with side effects"),
  ("sql159", "`CREATE TRIGGER ... FOR EACH STATEMENT ... NEW`"),
  ("sql160", "`pg_advisory_lock(...)` (session-level) without a matching `pg_advisory_unlock(...)` in the same source"),
  ("sql164", "`'foo' || 1` or `'a' + 1`"),
  ("sql166", "`ROW(x)` with a single element"),
  ("sql167", "`CREATE INDEX"),
  ("sql168", "`CREATE UNIQUE INDEX"),
  ("sql169", "`ALTER TABLE x OWNER TO some_role`"),
  (
    "sql170",
    "`x := <lit>` inside a PL/pgSQL body where the literal kind disagrees with x's declared type. Catches `DECLARE...",
  ),
  ("sql171", "`UPDATE t SET <col> = <literal>` where the literal kind disagrees with the column's catalog type"),
  (
    "sql172",
    "`<col> = <literal>` (or `<>`, `>`, `<`, `>=`, `<=`) where the literal kind disagrees with the column's...",
  ),
  ("sql173", "workspace CREATE TABLE diverges from the live catalog"),
  ("sql174", "`COUNT(col)` where `col` is nullable"),
  ("sql175", "`SELECT ... FROM <view> FOR UPDATE`"),
  ("sql176", "`WHERE col IS NULL` where the catalog says `col` is NOT NULL"),
  ("sql177", "`INSERT INTO t (a, ...) VALUES (NULL, ...)` where `a` is NOT NULL and has no default"),
  (
    "sql178",
    "Writing to a `GENERATED ALWAYS` column. PG rejects writes to identity/stored generated columns: * `INSERT...",
  ),
  (
    "sql179",
    "`SAVEPOINT s;` outside a transaction errors with 25P01 (\"SAVEPOINT can only be used in transaction blocks\")",
  ),
  ("sql180", "`TRUNCATE` inside a trigger function body"),
  (
    "sql181",
    "`INSERT INTO t (name) VALUES ('long-string')` where `name` is declared `VARCHAR(n)` and the literal exceeds n",
  ),
  (
    "sql182",
    "`INSERT INTO t (d) VALUES ('garbage')` where `d` is DATE / TIMESTAMP / TIMESTAMPTZ / TIME and the string...",
  ),
  (
    "sql183",
    "`INSERT INTO t (id) VALUES ('not-a-uuid')` where `id` is UUID. PG raises 22P02 at runtime. Accept only: *...",
  ),
  (
    "sql184",
    "integer literal larger than the column's declared type can hold (`SMALLINT` max 32767, `INT` max 2147483647)",
  ),
  ("sql185", "`REFERENCES other(missing)` where `missing` isn't a column on `other`"),
  ("sql186", "`ALTER TABLE t DROP COLUMN id` where another catalog table has a FK that references `t(id)`"),
  ("sql187", "`JOIN other USING (col)`"),
  ("sql188", "`COMMENT ON TABLE bogus IS '...'` where bogus isn't a known catalog table"),
  (
    "sql189",
    "`ALTER TABLE t ALTER COLUMN c TYPE <new_type>` where `c`'s catalog type doesn't auto-cast to `<new_type>` and...",
  ),
  (
    "sql190",
    "`INSERT INTO t (...) ... ON CONFLICT (col, ...) DO ...` where `(col, ...)` is not the target of any PRIMARY...",
  ),
  (
    "sql191",
    "`ROWS BETWEEN <n> FOLLOWING AND <m> PRECEDING` or any frame where the start bound is strictly later than the...",
  ),
  ("sql192", "`SELECT"),
  ("sql193", "`GENERATED ALWAYS AS (expr) STORED` where `expr` calls a known-volatile function (random / now /..."),
  ("sql194", "`TRUNCATE foo` (no CASCADE) when another table has an FK referencing `foo`"),
  ("sql195", "`CAST('lit' AS <type>)` or `'lit'::<type>` where `lit` can't be parsed as `<type>`"),
  (
    "sql196",
    "`REFERENCES other(col)` where `other.col` is not the target of a PRIMARY KEY or UNIQUE constraint / unique...",
  ),
  ("sql197", "`array_length(col, ...)`, `unnest(col)`, `cardinality(col)`, `array_to_string(col, ...)`..."),
  ("sql198", "inline column CHECK references a different column"),
  ("sql199", "`<col> <type> DEFAULT <expr>` where `<expr>` references another column on the same table"),
  ("sql200", "`JOIN LATERAL (SELECT"),
  ("sql201", "`CREATE FUNCTION"),
  (
    "sql202",
    "PL/pgSQL trigger function body references `OLD.*` inside an INSERT trigger or `NEW.*` inside a DELETE...",
  ),
  (
    "sql203",
    "`RAISE 'msg'` inside a PL/pgSQL body without a level keyword (NOTICE/INFO/LOG/WARNING/EXCEPTION/DEBUG). PG...",
  ),
  ("sql204", "`UPDATE users u SET other.col = ...`"),
  ("sql205", "`NOTIFY <channel>` where no `LISTEN <channel>` appears in the same buffer. Dead channel"),
  ("sql206", "`INSERT INTO t (a, b) VALUES ((SELECT 1, 2))`"),
  ("sql207", "`COALESCE(x)` with a single argument is a no-op"),
  ("sql208", "`EXTRACT(<field> FROM <expr>)` where `<field>` is not in the PG-supported list"),
  ("sql209", "`COPY t TO 'file.csv'` or `COPY t FROM 'file.csv'`"),
  ("sql210", "`REINDEX [CONCURRENTLY] (TABLE|INDEX) pg_<x>`"),
  ("sql211", "bare `ROLLBACK;` / `COMMIT;` with no preceding BEGIN / START TRANSACTION in the source"),
  ("sql212", "top-level `SELECT * INTO foo FROM bar`"),
  ("sql213", "`CREATE INDEX"),
  ("sql214", "`CREATE INDEX CONCURRENTLY` (or `DROP INDEX CONCURRENTLY`) inside an explicit transaction block"),
  ("sql215", "`GROUP BY ROLLUP(a)` / `CUBE(a)` with a single grouping column"),
  ("sql216", "`INSERT INTO t VALUES (1,2), (1,2,3)`"),
  ("sql217", "`SELECT ... LEFT JOIN ... FOR UPDATE`"),
  ("sql218", "`CASE WHEN ... THEN 1 ... WHEN ... THEN 'foo' ... END`"),
  ("sql219", "`COMMIT` / `ROLLBACK` inside a PL/pgSQL FUNCTION body"),
  ("sql220", "`WITH RECURSIVE t(...) AS (<single SELECT>) ...`"),
  ("sql221", "`ARRAY[1, 'foo']`"),
  ("sql222", "`SELECT * FROM (SELECT ... LIMIT N) FOR UPDATE`"),
  ("sql223", "`jsonb_set(col, 'key', '\"val\"')`"),
  (
    "sql224",
    "`SET CONSTRAINTS ALL DEFERRED` (or any SET CONSTRAINTS form) outside an explicit transaction block. The...",
  ),
  (
    "sql225",
    "`COMMENT ON ... IS NULL` (or `IS ''`) when the target already has a non-empty catalog comment. PG accepts this",
  ),
  ("sql226", "`DROP TABLE foo CASCADE` (or DROP TYPE/etc CASCADE) when the catalog shows 3+ direct dependents (FK..."),
  ("sql227", "`EXISTS (SELECT * FROM ...)`"),
  ("sql228", "`x = ANY (SELECT 1, 2 FROM ...)`"),
  (
    "sql229",
    "`WITH foo AS (UPDATE/INSERT/DELETE ...) SELECT * FROM foo` where the data-modifying CTE has no RETURNING...",
  ),
  ("sql230", "`CREATE INDEX ... USING GIN (col)` where `col` is a plain scalar (text/int/etc)"),
  ("sql231", "`NULLS FIRST` / `NULLS LAST` outside an ORDER BY clause"),
  ("sql232", "`<jsonb col> @> 'foo'` (or `<@`) where the RHS is a plain text literal without `::jsonb`"),
  ("sql233", "`CREATE MATERIALIZED VIEW mv"),
  ("sql234", "`WHERE col IN ()`"),
  ("sql235", "`pg_sleep(n)` inside an explicit transaction block"),
  ("sql236", "`AFTER` trigger function returns NEW/OLD row"),
  (
    "sql237",
    "A shell command (pg_dump, psql, pg_restore, createdb, dropdb) appears as the first token of a statement. PG...",
  ),
  ("sql238", "`<arr> = ARRAY[..., NULL, ...]`"),
  ("sql239", "`ALTER TABLE t DROP COLUMN c` where `c` was declared in a `CREATE TABLE t ("),
  ("sql240", "`SAVEPOINT s; ... SAVEPOINT s;`"),
  ("sql241", "`CREATE [OR REPLACE] VIEW v AS SELECT * FROM t`"),
  ("sql242", "`DROP SCHEMA foo` (no CASCADE / RESTRICT)"),
  ("sql243", "`FROM (VALUES (1, 2)) WHERE ...`"),
  ("sql244", "`CHECK (TRUE)` / `CHECK (1=1)` / `CHECK (1)` constraint is trivially satisfied"),
  ("sql245", "`FROM pg_class` (bare) instead of `FROM pg_catalog.pg_class`"),
  ("sql246", "`INSERT"),
  (
    "sql247",
    "`pg_advisory_lock(1)` (or `pg_advisory_xact_lock(1)`) with a hard-coded literal key. PG advisory locks are...",
  ),
  (
    "sql248",
    "`ALTER TABLE t ADD COLUMN c <type> NOT NULL` (no DEFAULT). On PG<11 PG rewrites the whole table to fill the...",
  ),
  ("sql249", "`INSERT INTO t DEFAULT VALUES`"),
  ("sql250", "`SELECT count(*) FROM t FOR UPDATE`"),
  ("sql251", "`SELECT * FROM t ORDER BY 1`"),
  ("sql252", "`SELECT * FROM (SELECT ... ORDER BY x) sub`"),
  ("sql253", "`x NOT IN (SELECT col FROM t)` where `col` is nullable"),
  (
    "sql254",
    "`ALTER TABLE t SET TABLESPACE ts` rewrites the entire table on disk and holds AccessExclusiveLock for the...",
  ),
  (
    "sql255",
    "`ROW_NUMBER() OVER ()` / `RANK() OVER ()` / `LAG() OVER ()` without an ORDER BY in the window definition",
  ),
  ("sql256", "`current_setting('foo')`"),
  ("sql257", "`DO $$ BEGIN SELECT now(); END $$;`"),
  ("sql258", "`SET LOCAL <foo> = <val>` outside an explicit transaction block"),
  ("sql259", "`SET ROLE <foo>` inside a CREATE FUNCTION body. Almost never intentional"),
  (
    "sql260",
    "`DROP FUNCTION foo` without an argument signature. On PG14+ this works when there's only one overload, but it...",
  ),
  ("sql261", "`MERGE INTO t USING src ON ... ;`"),
  ("sql262", "`CREATE EXTENSION pg_stat_statements` (without IF NOT EXISTS)"),
  (
    "sql263",
    "`SELECT * FROM (SELECT DISTINCT ON (k) ... FROM t) sub` without an ORDER BY inside the subquery. DISTINCT ON...",
  ),
  (
    "sql264",
    "`UPDATE pg_class SET ...` / `DELETE FROM pg_class` and other direct DML against `pg_catalog` system tables",
  ),
  ("sql265", "`CREATE TABLE t (..., c TIMESTAMP DEFAULT now(), ...)`"),
  ("sql266", "`jsonb_build_object(k1, v1, k2)`"),
  ("sql267", "`a = b = c` chained comparison"),
  ("sql268", "`(SELECT ... ORDER BY a) UNION (SELECT ...)`"),
  ("sql269", "`WHERE EXTRACT(YEAR FROM ts) = 2024` or `WHERE date_part('year', ts) = 2024`"),
  ("sql270", "`format('hello world')`"),
  ("sql271", "`DECLARE c CURSOR WITH HOLD FOR ...` outside an explicit transaction"),
  ("sql272", "`CREATE INDEX"),
  ("sql273", "`CHECK (FALSE)` / `CHECK (0)` constraint rejects every row"),
  (
    "sql274",
    "`SELECT ... INTO TEMP foo FROM bar` (or INTO TEMPORARY) where `foo` is also a real catalog table. PG allows it",
  ),
  ("sql275", "`SET TRANSACTION ...` (READ ONLY / READ WRITE / ISOLATION LEVEL) inside a CREATE FUNCTION body"),
  ("sql276", "`INTERVAL 1 DAY` style (no quotes)"),
  ("sql277", "`COMMENT ON FUNCTION foo IS '...'` without argument signature. Same hazard as DROP FUNCTION"),
  ("sql278", "`<expr> / 0` literal division by zero"),
  ("sql279", "`COMMENT ON CONSTRAINT pk_users IS '...'`"),
  ("sql280", "`ALTER TABLE t ADD CONSTRAINT c CHECK (...)` without `NOT VALID`"),
  ("sql281", "`ALTER TABLE t ALTER COLUMN c SET NOT NULL`"),
  ("sql282", "`WHERE 1=1 AND ...` / `WHERE TRUE AND ...`"),
  ("sql283", "`ANALYZE` (or `ANALYZE t`) inside an explicit transaction"),
  (
    "sql284",
    "`TG_OP`, `TG_TABLE_NAME`, `TG_RELID`, `TG_NAME`, `TG_WHEN`, `TG_LEVEL`, `TG_NARGS`, `TG_ARGV` referenced...",
  ),
  ("sql285", "`DROP ROLE foo` / `DROP USER foo` without a preceding `REASSIGN OWNED BY foo` + `DROP OWNED BY foo`"),
  ("sql286", "`ALTER TYPE x ADD VALUE 'new' BEFORE 'bogus'` where `bogus` is not one of `x`'s enum labels"),
  (
    "sql287",
    "`REVOKE ... CASCADE` on a privilege the grantee may have re-granted. CASCADE recursively revokes from every...",
  ),
  ("sql288", "`CREATE INDEX ON t (col)`"),
  ("sql289", "`CREATE TABLE ... INHERITS (parent)`"),
  (
    "sql290",
    "`percentile_cont(0.5)` / `percentile_disc(0.5)` / `mode()` without the required `WITHIN GROUP (ORDER BY ...)`...",
  ),
  ("sql291", "`GRANT ALL PRIVILEGES ON ...` (or bare `GRANT ALL`)"),
  ("sql292", "`LIMIT 0` returns zero rows"),
  ("sql293", "`NULLIF(1, 'foo')`"),
  (
    "sql294",
    "`BEGIN;` (or `START TRANSACTION;`) when an earlier BEGIN in the source hasn't been COMMITed / ROLLBACKed",
  ),
  ("sql295", "`COPY ... WITH (HEADER, FORMAT TEXT)`"),
  (
    "sql296",
    "`REINDEX` (TABLE / INDEX / SCHEMA / DATABASE) inside an open transaction. PG holds AccessExclusiveLock for...",
  ),
  ("sql297", "`NOTIFY chan, '<huge literal>'`"),
  ("sql298", "CREATE TABLE / FUNCTION / TYPE / INDEX / TRIGGER / CONSTRAINT name longer than 63 bytes"),
  ("sql299", "`PRIMARY KEY (a, a)` / `UNIQUE (a, a)`"),
  ("sql300", "`SELECT a, b, FROM t`"),
  ("sql301", "`COPY ... FROM PROGRAM 'cmd'` / `COPY ... TO PROGRAM 'cmd'`"),
  ("sql302", "`DROP TABLE foo` (or DROP INDEX/VIEW/TRIGGER/etc) without `IF EXISTS`"),
  ("sql303", "`ARRAY[]` (empty constructor) without a `::type[]` cast"),
  ("sql304", "CREATE TABLE foo (..., parent_id REFERENCES foo(id))"),
  ("sql305", "`FROM information_schema.<view>`"),
  ("sql306", "`WHERE id IN (1, 1, 2)`"),
  ("sql307", "`UPDATE ... LIMIT N` / `DELETE ... LIMIT N`"),
  ("sql308", "`TIMESTAMP(7)` / `TIME(7)` / `TIMESTAMPTZ(7)` etc"),
  ("sql309", "`REVOKE SELECT ON foo;`"),
  ("sql310", "line starts with `\\<letter>`"),
  (
    "sql311",
    "`string_agg(col, ',')` / `array_agg(col)` / `json_agg(col)` / `jsonb_agg(col)` without an `ORDER BY` clause...",
  ),
  ("sql312", "column declared `SERIAL` / `BIGSERIAL` / `SMALLSERIAL`"),
  ("sql313", "`CREATE TABLE t (...) COMMENT 'msg'`"),
  ("sql314", "`AUTO_INCREMENT`"),
  ("sql315", "`ENGINE=InnoDB` / `ENGINE=MyISAM` / similar"),
  ("sql316", "MySQL-only types (TINYINT, MEDIUMINT, LONGTEXT, etc)"),
  ("sql317", "`[identifier]` (square-bracket quoting)"),
  ("sql318", "`SELECT TOP 10 ...`"),
  ("sql319", "`ISNULL(x, y)` (MSSQL/MySQL) / `NVL(x, y)` (Oracle) / `IFNULL(x, y)` (MySQL)"),
  ("sql320", "`GETDATE()` / `SYSDATE` / `GETUTCDATE()`"),
  ("sql321", "standalone `GO`"),
  ("sql322", "`BEGIN TRAN`"),
  ("sql323", "`SELECT ... FROM DUAL`"),
  ("sql324", "`ROWNUM`"),
  ("sql325", "`CONNECT BY PRIOR ...`"),
  ("sql326", "`a.id = b.id(+)`"),
  ("sql327", "`CREATE TABLE foo (...)` without an explicit schema qualifier. Style hint: every CREATE TABLE in a..."),
  ("sql328", "REVOKE in a buffer that has no matching GRANT"),
  (
    "sql329",
    "`substring(text FROM <number>)` without a matching `FOR`. PG returns the rest of the string from the start...",
  ),
  ("sql331", "`DROP INDEX CONCURRENTLY` inside an explicit transaction"),
  ("sql332", "`pg_terminate_backend(...)` / `pg_cancel_backend(...)` invoked from an unprivileged buffer"),
  (
    "sql333",
    "`ON UPDATE CASCADE` on a column referenced as a primary key. ON UPDATE CASCADE is rarely the right choice on...",
  ),
  ("sql334", "`SELECT setseed(...)` without a nearby deterministic guard"),
  ("sql335", "explicit `TABLESPACE <name>` clause in a buffer that likely runs as a non-superuser migration"),
  ("sql336", "`bytea` literal `'\\\\xFF'` without the `E''` escape-string prefix"),
  ("sql337", "`GROUP BY` references a SELECT-list alias instead of the original column"),
  (
    "sql338",
    "`CREATE TABLE x PARTITION OF parent (LIKE base INCLUDING INDEXES ...)` INCLUDING INDEXES inside a PARTITION...",
  ),
  ("sql339", "`TRUNCATE` inside a PL/pgSQL function body that also has an `EXCEPTION` block"),
  ("sql340", "`NEW.id := <expr>` inside a `BEFORE INSERT` trigger body"),
  (
    "sql341",
    "`INSERT INTO t (col) VALUES (ARRAY[...])` where the array element family doesn't match the target column's...",
  ),
  ("sql342", "`BOOL_AND(col)` / `BOOL_OR(col)` / `EVERY(col)` on a nullable boolean column"),
  (
    "sql343",
    "`percent_rank() OVER (ORDER BY <col>)` / `cume_dist() OVER (ORDER BY <col>)` where `<col>` is a non-numeric...",
  ),
  (
    "sql344",
    "`ORDER BY <col> USING <op>` where the column's type family is one of the families that lacks a meaningful...",
  ),
  ("sql345", "`ALTER TABLE t RENAME COLUMN old TO new` while some `CREATE VIEW v AS SELECT ...` in the same buffer..."),
  ("sql346", "`CREATE INDEX"),
  ("sql347", "`ALTER TABLE t ENABLE|DISABLE TRIGGER ...`"),
  ("sql348", "function call whose name isn't in the live catalog, the built-in dsl-knowledge function table, or a..."),
  ("sql349", "`INSERT INTO t (col_list)` lists a column not in the target table's catalog"),
  ("sql350", "`INSERT/UPDATE/DELETE"),
  ("sql351", "`DELETE/UPDATE FROM t WHERE bogus`"),
  ("sql402", "duplicate FROM/JOIN alias in a single SELECT. Example: `SELECT * FROM users a, orders a`"),
  (
    "sql403",
    "ORDER BY references a column that doesn't exist in any in-scope table or projection alias. PG models ORDER BY...",
  ),
  ("sql404", "GROUP BY references a column that doesn't exist"),
  ("sql405", "HAVING references a column that doesn't exist"),
  (
    "sql406",
    "duplicate column in an INSERT column list or UPDATE SET assignment list. - `INSERT INTO t (a, b, a) VALUES...",
  ),
  ("sql407", "`WHERE 1=2` / `WHERE FALSE` / `WHERE 1<>1`"),
  ("sql408", "`WHERE col = col` (or `<col> OP <col>` for the same column on both sides)"),
  ("sql409", "`WHERE col BETWEEN col AND ...` or `WHERE col BETWEEN ... AND col`"),
  ("sql410", "`SELECT id, id FROM ...`"),
  (
    "sql411",
    "`LIMIT 1 OFFSET N` (with N > 0) without ORDER BY picks a deliberately non-first row, but without ORDER BY...",
  ),
  ("sql412", "`ORDER BY id, id` / `GROUP BY id, id`"),
  ("sql413", "`expr || NULL` / `NULL || expr`"),
  ("sql414", "`WHERE col IN (col, ...)` or `... col NOT IN (col, ...)`"),
  ("sql415", "`col::T` or `CAST(col AS T)` where T is the column's catalog data type"),
  ("sql416", "`CASE WHEN ... THEN x ... WHEN ... THEN x ELSE x END`"),
  ("sql417", "`COALESCE(a, a, ...)` or `COALESCE(a, NULL, ...)`"),
  ("sql418", "`SELECT DISTINCT pk_col FROM t`"),
  ("sql419", "`NULLIF(x, NULL)` and `NULLIF(NULL, x)` are pointless"),
  ("sql420", "`WHERE col = ANY(ARRAY[col, ...])`"),
  ("sql421", "`WHERE age > 0 AND age > 0`"),
  ("sql422", "`WHERE X AND NOT X`"),
  (
    "sql423",
    "`col ~ '^prefix'` (or `~* '^prefix'`) where the regex is just an anchored literal prefix could be rewritten...",
  ),
  ("sql424", "`WHERE count(*) > 1`"),
  ("sql425", "window function in WHERE / HAVING / JOIN ON"),
  ("sql426", "`SELECT DISTINCT id FROM users ORDER BY age`"),
  ("sql427", "`WHERE date(ts) = '2024-01-01'` / `WHERE ts::date = ...` / `WHERE CAST(ts AS date) = ...`"),
  ("sql428", "`MAX(*) / SUM(*) / AVG(*)` etc"),
  ("sql429", "`WHERE col == 1` (C-style) and `WHERE col <=> 1` (MySQL null-safe equal)"),
  ("sql430", "`SELECT *, col FROM t`"),
  ("sql431", "`SELECT"),
  ("sql432", "`CASE WHEN p THEN a WHEN p THEN b END`"),
  ("sql433", "`ORDER BY NULL` / `ORDER BY TRUE` / `ORDER BY 'foo'`"),
  ("sql434", "`WHERE col IS NOT NULL AND col = 5`"),
  ("sql435", "`WHERE col IS NULL AND col = 5` (or any strict op, or `col IS NOT NULL`)"),
  ("sql436", "`sum(row_number() OVER (...))`"),
  ("sql437", "`WHERE NULL IN (1, 2, 3)`"),
  ("sql438", "`id int GENERATED ALWAYS AS IDENTITY DEFAULT 0`"),
  ("sql439", "`DATE '2024-13-01'` / `TIMESTAMP '2024-02-30'`"),
  ("sql440", "`INTERVAL '2 mans'`"),
  ("sql441", "`WHERE EXISTS (SELECT 1 FROM other_table)`"),
  ("sql442", "`regexp_replace(s, pattern, replacement)`"),
  ("sql443", "`substring(s, start, -3)`"),
  ("sql444", "`generate_series(1, 10, 0)`"),
  ("sql445", "`array_position(arr, NULL)`"),
  ("sql446", "`position('' in s)` / `strpos(s, '')`"),
  ("sql447", "`power(x, 0)` always returns 1 and `power(x, 1)` always returns x"),
  ("sql448", "`lpad('hi', -3, '0')`"),
  ("sql449", "`jsonb_build_object('k', 1, 'k', 2)`"),
  ("sql450", "`NUMERIC(p, s)` (or `DECIMAL(p, s)`) with `s > p`"),
  ("sql451", "`VARCHAR(0)` / `CHAR(0)` / `CHARACTER(0)` / `CHARACTER VARYING(0)`"),
  ("sql452", "`repeat(s, 0)` or `repeat(s, -3)`"),
  ("sql453", "`array_length(arr)`"),
  ("sql454", "`to_timestamp(s, 'HH:MM')`"),
  ("sql455", "`WHERE X OR NOT X`"),
  ("sql456", "`WHERE smallint_col = 100000`"),
  ("sql457", "`SELECT a, b FROM t GROUP BY 3`"),
  ("sql458", "`SUM(bool_col)` / `AVG(bool_col)`"),
  ("sql459", "`COUNT(col)` where `col` is declared NOT NULL"),
  ("sql460", "`SELECT id FROM t HAVING id > 5`"),
  ("sql461", "`array_remove(NULL, 1)` / `array_position(NULL, 1)` / `cardinality(NULL)`"),
  ("sql462", "`x + NULL` (or `-`, `*`, `/`, `%`)"),
  ("sql463", "`IF TG_OP = 'inserted' THEN ...`"),
  ("sql464", "`x IS DISTINCT FROM x`"),
  ("sql465", "`concat_ws('', a, b, c)`"),
  ("sql466", "`... OFFSET 0`"),
  ("sql467", "`replace(s, '', x)` / `split_part(s, '', n)`"),
  ("sql468", "`GREATEST(NULL, NULL)` / `LEAST(NULL, NULL, NULL)`"),
  ("sql469", "`NOT (col IS NULL)` and `NOT col IS NULL`"),
  ("sql470", "`NOT (col IN (...))` / `NOT (col LIKE ...)` / `NOT (col BETWEEN ...)`"),
  ("sql471", "`WHERE x IN (SELECT DISTINCT y FROM t)`"),
  ("sql472", "`EXTRACT(dow FROM '1 day'::interval)`"),
  ("sql473", "`col = ANY(ARRAY[]::int[])`"),
  ("sql474", "`WHERE 'a' = 'a'` (tautology), `WHERE 2 = 2` (tautology), `WHERE 'a' = 'b'` (contradiction)"),
  ("sql475", "`INSERT INTO t SELECT ... FROM t`"),
  ("sql476", "`CASE col WHEN NULL THEN ...`"),
  ("sql477", "`col @> '{}'::jsonb` / `col @> '[]'::jsonb` / `col @> ARRAY[]::int[]`"),
  ("sql478", "`col <@ '{}'::jsonb` / `col <@ '[]'::jsonb` / `col <@ ARRAY[]::int[]`"),
  ("sql479", "`substring(s, 0, n)` / `substring(s FROM 0 FOR n)` / `substr(s, 0, n)`"),
  ("sql480", "`GROUP BY NULL` / `GROUP BY TRUE` / `GROUP BY 'foo'`"),
  ("sql481", "`position(<needle> in '')` / `strpos('', <needle>)`"),
  ("sql482", "`HAVING <constant>`"),
  ("sql483", "`split_part(<s>, <delim>, 0)`"),
  ("sql484", "`OVER (PARTITION BY <constant> ...)`"),
  (
    "sql485",
    "`regexp_split_to_array(s, '')`, `regexp_split_to_table(s, '')`, `regexp_match(s, '')`, `regexp_matches(s, '')`",
  ),
  ("sql486", "`SELECT DISTINCT *` / `SELECT DISTINCT t.*`"),
  ("sql487", "`array_length(arr, 0)`, `array_lower(arr, 0)`, `array_upper(arr, 0)`, or any negative dimension"),
  ("sql488", "`jsonb_path_exists/query/query_array/query_first/match(col, '<path>')`"),
  (
    "sql489",
    "`WHERE col + 0 = N`, `col - 0 = N`, `col * 1 = N`, `col / 1 = N` (and the commutative `0 + col`, `1 * col`)",
  ),
  ("sql490", "`col || ''` / `'' || col`"),
  ("sql491", "`HAVING 1 = 1` (tautology) / `HAVING 1 = 2` (contradiction) / `HAVING 'a' = 'b'`"),
  ("sql492", "`col NOT IN (..., NULL, ...)`"),
  ("sql493", "`COALESCE(<not-null-col>, ...)`"),
  ("sql494", "`jsonb_set(target, '{}', value)` / `jsonb_set_lax` / `jsonb_insert` with an empty path array"),
  ("sql495", "`WHERE col = ALL(<array-literal>)`"),
  ("sql496", "`UPDATE t SET col = DEFAULT` where `col` has no DEFAULT definition"),
  ("sql497", "`array_agg(DISTINCT a ORDER BY b)` and similar"),
  ("sql498", "`WHERE col SIMILAR TO 'pattern'`"),
  ("sql499", "`WHERE tsvector_col @@ 'plain text'`"),
  ("sql500", "`date_col1 - date_col2`"),
  ("sql501", "`ORDER BY not_null_col NULLS FIRST|LAST`"),
  ("sql502", "`WHERE timestamptz_col <op> TIMESTAMP 'lit'`"),
  ("sql503", "`WHERE non_jsonb_col ? 'key'` / `?|` / `?&`"),
  ("sql504", "`<int_col> / <int_literal>`"),
  ("sql505", "`<text_col> -> 'key'` / `->>` / `#>` / `#>>`"),
  ("sql506", "`ARRAY[NULL]` / `ARRAY[NULL, NULL, ...]`"),
  ("sql507", "`EXECUTE '<sql>' || <var>`"),
  (
    "sql508",
    "`WHERE col LIKE col` / `ILIKE` / `NOT LIKE` / `NOT ILIKE` and the POSIX-regex equivalents `~ / ~* / !~ / !~*`",
  ),
  (
    "sql509",
    "explicit `pg_temp.<table>` (or `pg_temp_<N>.<table>`) reference. Temporary tables live in a per-backend...",
  ),
  ("sql510", "`WHERE col SIMILAR TO col` / `NOT SIMILAR TO col`"),
  ("sql511", "`WHERE col @> col` / `col <@ col` / `col && col`"),
  (
    "sql512",
    "table-level PK / UNIQUE / FK source constraint references a column that isn't declared on this table. PG...",
  ),
  ("sql513", "function call arg-count validation"),
  (
    "sql514",
    "empty expression parentheses where an expression is required. Catches the post-refactor pattern where a...",
  ),
  ("sql515", "`WHERE col IN (1)` / `WHERE col NOT IN (1)`"),
  ("sql516", "`UPDATE t SET col = col`"),
  ("sql517", "`JOIN ... ON 1 = 1`"),
  ("sql518", "`CASE WHEN cond THEN TRUE ELSE FALSE END`"),
  ("sql519", "`WHERE a = 1 OR a = 2 OR a = 3`"),
  ("sql520", "`WHERE lower(col) = 'ABC'` / `WHERE upper(col) LIKE 'abc%'`"),
  ("sql521", "`col = ANY(ARRAY[1])` / `col <> ALL(ARRAY['x'])`"),
  ("sql522", "`a LEFT JOIN b ON ... WHERE b.col = 'x'`"),
  ("sql523", "`WHERE col IS NULL OR col IS NOT NULL`"),
  ("sql524", "`col LIKE '%'`"),
  ("sql525", "`EXISTS (SELECT ... LIMIT 1)`"),
  ("sql526", "`WHERE col = 1 AND col = 2`"),
  ("sql527", "`WHERE col > 5 AND col < 3`"),
  ("sql528", "`REPLACE(s, x, x)`"),
  ("sql529", "`HAVING COUNT(*) > 0`"),
  ("sql530", "`COALESCE(COALESCE(a, b), c)`"),
  ("sql531", "`SELECT name AS name`"),
  ("sql532", "`SELECT"),
  ("sql533", "`col BETWEEN 5 AND 5`"),
  ("sql534", "`GREATEST(x, x)` / `LEAST(a, b, a)`"),
  ("sql535", "`WHERE a <> 1 AND a <> 2 AND a <> 3`"),
  ("sql536", "`INSERT ... ON CONFLICT ... DO UPDATE SET col = col`"),
  ("sql537", "`NOT (a = b)`"),
  ("sql538", "`ROUND(x, 0)` / `TRUNC(x, 0)`"),
  ("sql539", "`SELECT DISTINCT(col), other ...` (or `COUNT(DISTINCT(col))`)"),
  ("sql540", "`WHERE length(s) = 0` / `length(s) > 0`"),
  ("sql541", "a boolean literal operand that forces the whole condition to a constant"),
  ("sql542", "`now()::date` / `current_timestamp::date`"),
  ("sql543", "`GROUP BY count(*)` / `GROUP BY sum(x)`"),
  ("sql544", "`WHERE col >= 5 AND col <= 5`"),
  ("sql545", "`WHERE EXTRACT(MONTH FROM x) = 13` / `EXTRACT(DOW FROM x) = 7`"),
  ("sql546", "`WHERE x % 7 = 7`"),
  ("sql547", "`WHERE array_length(arr, 1) = 0`"),
  ("sql548", "`col <> ALL(ARRAY[1, 2, 3])`"),
  ("sql549", "`FROM users AS users` / `JOIN orders orders`"),
  ("sql550", "`WHERE x > 5 AND x > 3`"),
  (
    "sql551",
    "redundantly nested functions whose outer call subsumes the inner one: * `upper(lower(x))` / `lower(upper(x))`...",
  ),
  ("sql552", "`WHERE abs(x) < 0` / `cardinality(arr) = -1`"),
  ("sql553", "`CREATE TABLE t (col int DEFAULT NULL)`"),
  ("sql554", "the operator spellings of LIKE"),
  ("sql555", "`WHERE active IS TRUE` / `WHERE active IS FALSE`"),
  ("sql556", "`col = ANY(ARRAY[1, 2, 3])`"),
  ("sql557", "`CREATE TABLE t (id int, id text)`"),
  ("sql558", "a `CREATE TABLE` with more than one PRIMARY KEY definition (e.g"),
  ("sql559", "`CREATE INDEX idx ON t (a, b, a)`"),
  ("sql560", "`FOREIGN KEY (a, b) REFERENCES t (c)`"),
  ("sql561", "`SELECT ... LIMIT ALL`"),
  ("sql562", "`col int DEFAULT (SELECT max(id) FROM t)`"),
  ("sql563", "`col = ANY(ARRAY[1, 2, 1])`"),
  ("sql564", "`CREATE TABLE t (a int NULL NOT NULL)`"),
  (
    "sql565",
    "`col - col` (always 0) and `col / col` (always 1, or a division-by-zero error when `col` is 0). Subtracting...",
  ),
  ("sql566", "`WHERE x = x + 1`"),
  ("sql567", "common built-in functions called with too few arguments"),
  ("sql568", "`col ~ 'abc'`"),
  ("sql569", "`EXISTS (SELECT ... ORDER BY ...)`"),
  ("sql570", "`EXISTS (SELECT DISTINCT ...)`"),
  ("sql571", "`CREATE ROLE app PASSWORD 'hunter2'`"),
  ("sql572", "`CREATE ROLE deploy SUPERUSER` / `ALTER ROLE app SUPERUSER`"),
  ("sql573", "`CREATE ROLE etl BYPASSRLS` / `ALTER ROLE app BYPASSRLS`"),
  ("sql574", "`ALTER TABLE t DISABLE ROW LEVEL SECURITY`"),
  ("sql575", "`CREATE POLICY p ON t USING (true)` (or `WITH CHECK (true)`)"),
  ("sql576", "`ALTER TABLE t DISABLE TRIGGER ALL`"),
  ("sql577", "`CREATE VIEW v AS SELECT ... ORDER BY x`"),
  ("sql578", "`CREATE RULE ...`"),
  ("sql579", "`... WITH (autovacuum_enabled = false)` / `ALTER TABLE t SET (autovacuum_enabled = off)`"),
  ("sql580", "`CREATE UNLOGGED TABLE ...` (or `ALTER TABLE ... SET UNLOGGED`)"),
  (
    "sql581",
    "a `json` column type (or `::json` cast). `jsonb` is almost always the better choice: it's stored decomposed...",
  ),
  ("sql582", "the `money` column type"),
  ("sql583", "`EXISTS (SELECT ... GROUP BY x)` with no HAVING"),
  ("sql584", "the internal `pg_catalog` type aliases (`int4`, `int8`, `float8`, `serial4`, ...) in DDL"),
  (
    "sql585",
    "a `CLUSTER` command. It physically rewrites the whole table in index order under an ACCESS EXCLUSIVE lock...",
  ),
  (
    "sql586",
    "`VACUUM FULL` rewrites the entire table (and its indexes) into new files under an ACCESS EXCLUSIVE lock...",
  ),
  ("sql587", "`ALTER TABLE t ADD COLUMN c uuid DEFAULT gen_random_uuid()`"),
  ("sql588", "`ALTER TABLE t ADD PRIMARY KEY (...)` / `ADD UNIQUE (...)`"),
  ("sql589", "`ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (a) REFERENCES b (c)` without `NOT VALID`"),
  ("sql590", "a `REINDEX` without `CONCURRENTLY`"),
  ("sql591", "`VALUES (1, 2), (3, 4, 5)`"),
  ("sql592", "`WHERE 1` / `WHERE 0`"),
  ("sql593", "`LIMIT 10, 20`"),
  ("sql594", "`INSERT ... ON DUPLICATE KEY UPDATE ...`"),
  ("sql595", "`REPLACE INTO t ...`"),
  ("sql596", "MySQL-only functions that don't exist in PostgreSQL"),
  ("sql597", "`col REGEXP 'pat'` / `col RLIKE 'pat'`"),
  ("sql598", "`USE mydb`"),
  ("sql599", "`int unsigned` / `bigint unsigned`"),
  ("sql600", "`` `col` ``"),
  ("sql601", "`VARCHAR2(n)` / `NVARCHAR2(n)`"),
  ("sql602", "`DECODE(expr, search, result [, ...] [, default])`"),
  ("sql603", "`... MINUS ...`"),
  ("sql604", "`CLOB` / `NCLOB`"),
  (
    "sql605",
    "an inline foreign-key column declared `NOT NULL` but with an `ON DELETE SET NULL` / `ON UPDATE SET NULL`...",
  ),
  ("sql606", "a `CHECK` constraint whose expression contains a subquery (e.g"),
  ("sql607", "a length/precision modifier on a type that doesn't accept one"),
  ("sql608", "`CREATE UNIQUE INDEX"),
  ("sql609", "`SELECT DISTINCT ... FOR UPDATE`"),
  ("sql610", "`SELECT ... OVER (...) ... FOR UPDATE`"),
  ("sql611", "`UPDATE ... ORDER BY` / `DELETE ... ORDER BY`"),
  ("sql612", "an aggregate function in a `RETURNING` list"),
  (
    "sql613",
    "`col ... GENERATED ALWAYS AS (expr)` without the `STORED` keyword (or written `... VIRTUAL`). PostgreSQL only...",
  ),
  (
    "sql614",
    "a MySQL-style inline `KEY ...` / `INDEX ...` definition inside `CREATE TABLE`. PostgreSQL doesn't allow...",
  ),
  ("sql615", "the `WITH OIDS` table option"),
  (
    "sql616",
    "a MySQL `CHARACTER SET ...` / `CHARSET=...` clause (per-column or per-table). PostgreSQL has no per-column or...",
  ),
  (
    "sql617",
    "`NATURAL JOIN` (and `NATURAL LEFT/RIGHT/FULL JOIN`). A natural join implicitly joins on *every* pair of...",
  ),
  ("sql618", "`FETCH FIRST n ROWS WITH TIES` without an `ORDER BY`"),
  (
    "sql619",
    "`date_trunc('<unit>', ...)` where `<unit>` is a string literal that isn't one of PostgreSQL's recognised...",
  ),
  ("sql620", "MySQL / SQL Server date arithmetic functions that don't exist in PostgreSQL"),
  ("sql621", "the MySQL `IF(cond, then, else)` function"),
  ("sql622", "MySQL-only string functions that don't exist in PostgreSQL"),
  ("sql623", "a MySQL inline `ENUM('a','b',...)` column type"),
  (
    "sql624",
    "the MySQL column attribute `ON UPDATE CURRENT_TIMESTAMP` (auto-touch a timestamp column on every row update)",
  ),
  ("sql625", "the MySQL `ZEROFILL` column attribute (left-pads a numeric column with zeros on display, and implies..."),
  ("sql626", "MySQL-only query modifiers / hints that have no PostgreSQL equivalent and are syntax errors in PG"),
  ("sql627", "the MySQL infix operators `XOR` (logical exclusive-or) and `DIV` (integer division)"),
  ("sql628", "scalar functions from Oracle / SQL Server / MySQL that don't exist in PostgreSQL"),
  ("sql629", "SQL Server (T-SQL) data types that don't exist in PostgreSQL"),
  ("sql630", "SQL Server (T-SQL) identity / GUID functions that don't exist in PostgreSQL"),
  (
    "sql631",
    "`last_value(...)` / `nth_value(...)` over a window that has an `ORDER BY` but no explicit frame clause. The...",
  ),
  (
    "sql632",
    "the server-side large-object file functions `lo_import('path')` and `lo_export(oid, 'path')`. They read/write...",
  ),
  ("sql633", "server-side filesystem functions `pg_read_file`, `pg_read_binary_file`, `pg_ls_dir`, and `pg_stat_file`"),
  ("sql634", "`gen_salt('md5' | 'des' | 'xdes')` from pgcrypto. These algorithms are weak for password hashing"),
  ("sql635", "a `PRAGMA ...` statement"),
  ("sql636", "the SQLite `AUTOINCREMENT` keyword (one word, e.g"),
  ("sql637", "the SQLite `GLOB` operator (case-sensitive, Unix-glob pattern match, e.g"),
  ("sql638", "SQLite-only functions that don't exist in PostgreSQL"),
  ("sql639", "more cross-dialect string functions absent from PostgreSQL"),
  ("sql640", "MySQL date-part functions with no PostgreSQL equivalent"),
  (
    "sql641",
    "a `DEFAULT` of the special relative date/time strings `'now'`, `'today'`, `'tomorrow'`, or `'yesterday'`....",
  ),
  ("sql642", "MySQL file-I/O syntax"),
  ("sql643", "Oracle scalar functions absent from PostgreSQL"),
  ("sql644", "MySQL date-arithmetic functions absent from PostgreSQL"),
  (
    "sql645",
    "a set-returning function (`generate_series`, `unnest`, `jsonb_array_elements`, `regexp_split_to_table`...",
  ),
  (
    "sql646",
    "`count(DISTINCT *)` (or any aggregate with `DISTINCT *`). PostgreSQL doesn't support `DISTINCT *` inside an...",
  ),
  ("sql647", "`<col> IN (SELECT a, b,"),
  (
    "sql648",
    "`TABLESAMPLE SYSTEM (p)` / `TABLESAMPLE BERNOULLI (p)` where the literal sampling percentage `p` is outside `0",
  ),
  (
    "sql649",
    "`INSERT ... ON CONFLICT DO UPDATE ...` with no conflict target. `DO UPDATE` needs to know *which* unique...",
  ),
  ("sql650", "a row-constructor comparison with unequal arity, e.g"),
  ("sql651", "a set-returning function (`generate_series`, `unnest`, `jsonb_array_elements`, ...) in a `GROUP BY`..."),
  ("sql652", "two common-table expressions in the same `WITH` clause share a name, e.g"),
  ("sql653", "an aggregate function inside a `CHECK` constraint, e.g"),
  ("sql654", "an aggregate function in a `CREATE INDEX` expression, e.g"),
  ("sql655", "a multi-column UPDATE assignment whose column list and value list have different lengths, e.g"),
  (
    "sql656",
    "a `TRUNCATE` statement with a `WHERE` clause. TRUNCATE removes *all* rows of a table and accepts no row filter",
  ),
  ("sql657", "an `ORDER BY` that appears after `LIMIT` / `OFFSET` / `FETCH` at the top level of a query"),
  (
    "sql658",
    "both a `LIMIT` clause and a `FETCH FIRST/NEXT ... ROWS` clause in the same query level. They're two spellings...",
  ),
  (
    "sql659",
    "a `WHERE` clause that appears after `GROUP BY` at the top level of a query. SQL fixes the order as `... WHERE...",
  ),
  ("sql660", "a `CROSS JOIN` with an `ON` or `USING` clause"),
  (
    "sql661",
    "a window-only function (`row_number`, `rank`, `dense_rank`, `lag`, `lead`, `ntile`, `first_value`, ...)...",
  ),
  ("sql662", "`SELECT DISTINCT ON <expr>` without parentheses around the expression list"),
  ("sql663", "an `ORDER BY` / `LIMIT` / `OFFSET` / `FETCH` clause that appears before a set operation (`UNION` /..."),
  ("sql664", "a `HAVING` clause that appears before `GROUP BY` at the top level"),
  ("sql665", "an `UPDATE` whose `WHERE` clause comes before `SET`, e.g"),
  ("sql666", "`INSERT IGNORE INTO ...`"),
  ("sql667", "MySQL's `INSERT INTO t SET a = 1, b = 2` assignment-list syntax"),
  ("sql668", "a `DELETE` whose first token isn't `FROM`, e.g"),
  ("sql669", "MySQL's `SELECT"),
  ("sql670", "a MySQL `SHOW TABLES` / `SHOW DATABASES` / `SHOW COLUMNS` / `SHOW CREATE TABLE` /"),
  ("sql671", "a `DESCRIBE t` / `DESC t` statement (MySQL / Oracle table introspection)"),
  ("sql672", "MySQL's `ALTER TABLE"),
  ("sql673", "`x BETWEEN NULL AND y` / `x BETWEEN y AND NULL`"),
  (
    "sql674",
    "a ranking window function with an explicit frame clause, e.g. `ROW_NUMBER() OVER (ORDER BY x ROWS BETWEEN...",
  ),
  ("sql675", "`SELECT DISTINCT ... UNION SELECT ...`"),
  ("sql676", "`COUNT(DISTINCT 1)` / `COUNT(DISTINCT 'x')`"),
  ("sql677", "`x % 1` / `MOD(x, 1)`"),
  (
    "sql678",
    "the MySQL \"zero date\" literal `'0000-00-00'` (or `'0000-00-00 00:00:00'`). MySQL accepts it as a placeholder...",
  ),
  ("sql679", "`left(s, 0)` / `right(s, 0)`"),
  ("sql680", "`substring(s FROM n FOR 0)` / `substr(s, n, 0)`"),
  ("sql681", "`x * 0` / `0 * x`"),
  ("sql682", "`COALESCE(COUNT(...), 0)`"),
  ("sql683", "`CASE WHEN TRUE THEN ...` / `CASE WHEN FALSE THEN ...`"),
  ("sql684", "`GREATEST(a, NULL, b)` / `LEAST(x, NULL)`"),
  ("sql685", "`power(1, x)` always returns 1"),
  ("sql686", "`NOT NOT x` / `NOT (NOT x)`"),
  ("sql687", "`COALESCE('x', ...)`"),
  ("sql688", "`concat_ws(NULL, a, b)`"),
  ("sql689", "`col % col`"),
  ("sql690", "`sqrt(-1)`"),
  ("sql691", "`min(DISTINCT x)` / `max(DISTINCT x)`"),
  ("sql692", "`ln(0)` / `ln(-1)` / `log(0)` / `log(-5)`"),
  ("sql693", "`log(1, x)`"),
  ("sql694", "`acos(2)` / `asin(-3)`"),
  ("sql695", "an aggregate call nested directly inside another aggregate, e.g"),
  ("sql696", "`count(coalesce(x, 0))`"),
  ("sql697", "`degrees(radians(x))` / `radians(degrees(x))`"),
  ("sql698", "`chr(0)`"),
  ("sql699", "`lpad(s, 0)` / `rpad(s, 0)`"),
  ("sql700", "`setseed(2)`"),
  ("sql701", "`NULLIF('a', 'b')` / `NULLIF(1, 2)`"),
  ("sql702", "`COALESCE(x, 0) IS NULL`"),
  ("sql703", "`ntile(0)` / `ntile(-2)`"),
  ("sql704", "`nth_value(x, 0)` / `nth_value(x, -1)`"),
  ("sql705", "`width_bucket(x, lo, hi, 0)`"),
  ("sql706", "`array_to_string(arr, NULL)`"),
  ("sql707", "`lag(x, 0)` / `lead(x, 0)`"),
  ("sql708", "`lpad(s, n, NULL)` / `rpad(s, n, NULL)`"),
  ("sql709", "`jsonb_typeof(x) = 'int'`"),
  ("sql710", "`COALESCE(x, 0) IS NOT NULL`"),
  ("sql711", "`make_date(2024, 13, 1)`"),
  ("sql712", "`make_time(25, 0, 0)`"),
  ("sql713", "`x & 0` / `0 & x`"),
  ("sql714", "`col & col` / `col | col`"),
  ("sql715", "`starts_with(x, '')`"),
  ("sql716", "`translate(s, '', to)`"),
  ("sql717", "`to_char(x, '')`"),
  ("sql718", "`repeat(s, 1)`"),
  ("sql719", "`CREATE SEQUENCE ... INCREMENT 0` (or `INCREMENT BY 0`, also in `ALTER SEQUENCE`)"),
  ("sql720", "`power(0, -1)`"),
  ("sql721", "`make_timestamp(2024, 13, 1, 0, 0, 0)`"),
  ("sql722", "`factorial(-1)`"),
  ("sql723", "`array_cat(a, '{}')` / `array_cat(ARRAY[], a)`"),
  ("sql724", "`NUMERIC(2000)` / `DECIMAL(0, 0)`"),
  ("sql725", "`random() >= 1` / `random() < 0`"),
  ("sql726", "`ascii('')`"),
  ("sql727", "`exp(ln(x))` / `ln(exp(x))`"),
  ("sql728", "`x | 0` / `0 | x`"),
  ("sql729", "`x << 0` / `x >> 0`"),
  ("sql730", "`chr(2000000)` / `chr(-1)`"),
  ("sql731", "`ln(1)` / `log(1)`"),
  ("sql732", "`acosh(0)` / `atanh(1)`"),
  ("sql733", "a string literal containing `password=...`"),
  ("sql734", "`x ILIKE 'plain'`"),
  ("sql735", "`EXISTS (SELECT count(*) FROM ...)`"),
  ("sql736", "`width_bucket(x, 5, 5, 10)`"),
  ("sql737", "`date_bin('0 seconds', ts, origin)`"),
  ("sql738", "comparing a never-negative function against a negative value (or `< 0`), so the predicate never matches"),
  ("sql739", "`x::int::int` / `(a || b)::text::text`"),
  ("sql740", "`NOT TRUE` / `NOT FALSE`"),
  ("sql741", "`x % -1` / `MOD(x, -1)`"),
  ("sql742", "`array_remove(arr, NULL)`"),
  ("sql743", "`array_replace(arr, x, x)`"),
  ("sql744", "`array_position(arr, x) = 0`"),
  ("sql745", "`date_part('yearr', ts)`"),
  ("sql746", "`int4range(5, 1)` / `numrange(10, 2)`"),
  ("sql747", "`percentile_cont(1.5) WITHIN GROUP (...)`"),
  ("sql748", "`encode(data, 'base32')`"),
  ("sql749", "`daterange('2024-01-01', '2023-01-01')`"),
  ("sql750", "`B'1021'`"),
  ("sql751", "`X'1G'`"),
  ("sql752", "`LIKE 'a%' ESCAPE '\\\\!'`"),
  ("sql753", "`setweight(tsv, 'E')`"),
  ("sql754", "`to_tsquery('quick brown fox')`"),
  ("sql755", "`count(DISTINCT a, b)`"),
  ("sql756", "`string_agg(x)` / `jsonb_object_agg(k)`"),
  (
    "sql757",
    "a partitioned table's PRIMARY KEY does not include every partition key column. PostgreSQL requires every...",
  ),
  (
    "sql758",
    "`FOR VALUES FROM (x) TO (y)` where the lower partition bound is not strictly less than the upper bound....",
  ),
  ("sql759", "`PARTITION BY RANGE/LIST/HASH (some_volatile_fn(col))`"),
  ("sql760", "`PARTITION BY RANGE/LIST/HASH (a, a)`"),
  ("sql761", "`ALTER TABLE ... DETACH PARTITION ... CONCURRENTLY` inside an explicit transaction. Like `DROP INDEX..."),
  ("sql762", "`FOR VALUES WITH (MODULUS m, REMAINDER r)` where the remainder is not less than the modulus"),
  ("sql763", "`JSON_EXISTS(doc, 'literal')` where the literal path string does not start with `$`"),
  ("sql764", "`JSON_VALUE("),
  ("sql765", "`JSON_QUERY(... WITH WRAPPER ... OMIT QUOTES)`"),
  ("sql766", "`JSON_TABLE(... COLUMNS (a ..., a ...))`"),
  ("sql767", "`col IS JSON` where the catalog already types `col` as `json` or `jsonb`"),
  (
    "sql768",
    "`<expr> IS JSON OBJECT AND <same expr> IS JSON ARRAY` (or any two different IS JSON kinds directly ANDed...",
  ),
  ("sql769", "`CYCLE"),
  ("sql770", "the recursive term references the CTE itself more than once"),
  ("sql771", "the recursive term contains an aggregate function call"),
  ("sql772", "the recursive term contains a top-level ORDER BY, LIMIT, or DISTINCT"),
  ("sql773", "the recursive term's self-reference sits on the nullable side of an outer join"),
  ("sql774", "`EXCLUDE USING <am> (col WITH op, col WITH op)`"),
  ("sql775", "`EXCLUDE USING btree/hash/brin/gin (...)`"),
  ("sql776", "`EXCLUDE USING gist (col WITH =)` on a single column with only the `=` operator"),
  ("sql777", "`CREATE DOMAIN ... CHECK (expr)` where `expr` never references `VALUE`"),
  (
    "sql778",
    "`CREATE DOMAIN ... CHECK (VALUE <op> <literal>) DEFAULT <literal>` where the DEFAULT literal plainly fails...",
  ),
  ("sql779", "`CREATE TYPE ... AS (a int, a text)`"),
  ("sql780", "`jsonb_path_exists(doc, '$.a ? (1 == 2)')`"),
  ("sql781", "`jsonb_array_length('{\"a\":1}'::jsonb)`"),
  ("sql782", "`'{\"a\":1}'::jsonb - 0`"),
  ("sql783", "`jsonb_build_object(NULL, 1, ...)`"),
  ("sql784", "`GROUPING SETS ((a,b), (a,b))`"),
  ("sql785", "`GROUPING(x)` where `x` does not appear anywhere in the statement's GROUP BY clause"),
  ("sql786", "`ROLLUP (a, a)` / `CUBE (a, a)`"),
  (
    "sql787",
    "a parenthesized `(SELECT ...)` subquery, correlated to the outer query (references a qualified column whose...",
  ),
  ("sql788", "a `LATERAL (...)` subquery references a table alias that's introduced later in the same FROM/JOIN list"),
  ("sql789", "`a FULL [OUTER] JOIN b ON ... WHERE b.col = 'x'`"),
  ("sql790", "`col type NOT NULL UNIQUE NULLS NOT DISTINCT`"),
  (
    "sql791",
    "`CREATE STATISTICS name (ndistinct)` (or `dependencies`) with fewer than 2 columns/expressions in the `ON`...",
  ),
  ("sql792", "`CREATE STATISTICS ... ON a, a FROM t`"),
  (
    "sql793",
    "an unconditional `WHEN MATCHED THEN` clause appears before another `WHEN MATCHED [AND ...] THEN` clause in...",
  ),
  ("sql794", "`WHEN NOT MATCHED THEN INSERT ... VALUES (target.col, ...)`"),
  ("sql795", "`CREATE PUBLICATION ... FOR TABLES IN SCHEMA s, s`"),
  ("sql796", "`CREATE SUBSCRIPTION ... WITH (create_slot = false)` with no `slot_name`"),
  ("sql797", "`CREATE PUBLICATION ... FOR TABLE a, a`"),
  ("sql798", "a bare `LOOP ... END LOOP` (not FOR/WHILE) whose body contains no `EXIT`, `RETURN`, or `RAISE` anywhere"),
  ("sql799", "a `FOR i IN ...` loop variable name shadows a column that exists somewhere in the connected catalog"),
  ("sql800", "`EXCEPTION WHEN OTHERS THEN` with an empty or `NULL;`-only body"),
  (
    "sql801",
    "`EXECUTE <dynamic sql> USING a, b` where the highest `$N` placeholder referenced in the dynamic SQL text...",
  ),
  (
    "sql802",
    "`EXECUTE '<literal SELECT>' INTO a, b` where the statically-known SELECT-list column count doesn't match the...",
  ),
  ("sql803", "`RAISE NOTICE` appears inside a loop body (bare `LOOP`, `FOR ... LOOP`, or `WHILE ... LOOP`)"),
  ("sql804", "a PL/pgSQL `DECLARE x type;` variable that's never referenced anywhere after `BEGIN`"),
];
